name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_pgsql, gd
          ini-values: post_max_size=256M, memory_limit=512M

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

      - name: Build frontend
        run: |
          npm ci
          npm run build

      - name: Prepare Laravel (migrate)
        env:
          APP_ENV: production
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 5432
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SSLMODE: require
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        run: |
          php artisan key:generate --force
          php artisan config:cache
          php artisan migrate --force
          php artisan storage:link || true

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'website-gis'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .