name: Build and Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Sesuaikan dengan versi PHP di App Service Anda
          extensions: mbstring, xml, ctype, curl, fileinfo, gd, bcmath, zip, soap, pdo, pdo_pgsql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --no-progress --no-dev --prefer-dist --optimize-autoloader

      - name: Build frontend
        run: |
          npm ci
          npm run build

      - name: Prepare Laravel for production
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'website-gis' # Ganti dengan nama App Service Anda
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Azure Login
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Run remote commands (migrate, storage link)
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp ssh --name website-gis --resource-group <YOUR_RESOURCE_GROUP> --command "cd /home/site/wwwroot && php artisan migrate --force && php artisan storage:link"