name: Build and Deploy Laravel App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # === PHP Dependencies (Composer) ===
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      # === Node.js Dependencies (NPM) ===
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM dependencies
        run: npm ci

      # === Detect changes only in frontend ===
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend:
              - 'resources/js/**'
              - 'resources/css/**'

      # === Cache Vite Build Output ===
      - name: Cache Vite build
        uses: actions/cache@v3
        with:
          path: public/build
          key: ${{ runner.os }}-vite-${{ hashFiles('resources/js/**', 'resources/css/**') }}
          restore-keys: |
            ${{ runner.os }}-vite-

      - name: Build frontend assets
        if: steps.changes.outputs.frontend == 'true'
        run: npm run build

      # === Laravel Optimizations ===
      - name: Laravel Optimize
        run: php artisan config:cache && php artisan route:cache && php artisan view:cache

      - name: Upload artifact for deploy
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'website-gis'
          slot-name: 'Production'
          package: .
